-- Web3Star: 관리자 패널 — 스키마 확장, 감사 로그, RLS 보조 트리거, SECURITY DEFINER RPC
-- Supabase Dashboard → SQL Editor 에서 한 번 실행 (또는 migrations 로 분할 배포).
--
-- 적용 후 첫 관리자 지정 (본인 이메일로 교체):
--   UPDATE public.users SET role = 'admin' WHERE email = 'your@email.com';
--
-- 클라이언트는 anon 키만 사용합니다. 크로스 사용자 조회/수정은 아래 RPC만 호출하세요.

-- ---------------------------------------------------------------------------
-- 1) users 컬럼 확장
-- ---------------------------------------------------------------------------
ALTER TABLE public.users
  ADD COLUMN IF NOT EXISTS role text NOT NULL DEFAULT 'user'
    CHECK (role IN ('user', 'vip', 'admin'));

ALTER TABLE public.users
  ADD COLUMN IF NOT EXISTS account_status text NOT NULL DEFAULT 'active'
    CHECK (account_status IN ('active', 'suspended', 'deleted'));

ALTER TABLE public.users
  ADD COLUMN IF NOT EXISTS mining_disabled boolean NOT NULL DEFAULT false;

COMMENT ON COLUMN public.users.role IS 'user | vip | admin — admin만 RPC로 타인 변경 가능';
COMMENT ON COLUMN public.users.account_status IS 'active | suspended | deleted';
COMMENT ON COLUMN public.users.mining_disabled IS 'true면 채굴/적립 로직에서 차단(앱에서 확인 필요)';

-- ---------------------------------------------------------------------------
-- 2) 감사 로그 (직접 INSERT 금지 — RPC에서만 기록)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.admin_audit_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  admin_id uuid NOT NULL REFERENCES public.users (id) ON DELETE CASCADE,
  action text NOT NULL,
  target_user_id uuid REFERENCES public.users (id) ON DELETE SET NULL,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS admin_audit_log_created_at_idx ON public.admin_audit_log (created_at DESC);
CREATE INDEX IF NOT EXISTS admin_audit_log_target_idx ON public.admin_audit_log (target_user_id);

ALTER TABLE public.admin_audit_log ENABLE ROW LEVEL SECURITY;

-- 관리자도 클라이언트에서 직접 읽지 않음 — 목록은 RPC로만 (선택: service_role 대시보드 조회)
DROP POLICY IF EXISTS "admin_audit_no_client" ON public.admin_audit_log;
CREATE POLICY "admin_audit_no_client" ON public.admin_audit_log FOR ALL USING (false);

-- ---------------------------------------------------------------------------
-- 3) 환전/출금 요청 (승인 플로우)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.withdrawal_requests (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES public.users (id) ON DELETE CASCADE,
  amount bigint NOT NULL CHECK (amount > 0),
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  note text,
  decided_at timestamptz,
  decided_by uuid REFERENCES public.users (id),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS withdrawal_requests_status_idx ON public.withdrawal_requests (status, created_at DESC);

ALTER TABLE public.withdrawal_requests ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "withdrawal_own_select" ON public.withdrawal_requests;
CREATE POLICY "withdrawal_own_select" ON public.withdrawal_requests
  FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "withdrawal_own_insert" ON public.withdrawal_requests;
CREATE POLICY "withdrawal_own_insert" ON public.withdrawal_requests
  FOR INSERT WITH CHECK (auth.uid() = user_id);

-- ---------------------------------------------------------------------------
-- 4) 미션 / 이벤트 (관리 UI용 최소 스키마)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.missions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  description text,
  reward_points int NOT NULL DEFAULT 0 CHECK (reward_points >= 0),
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.missions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "missions_public_read_active" ON public.missions;
CREATE POLICY "missions_public_read_active" ON public.missions
  FOR SELECT USING (active = true);

CREATE TABLE IF NOT EXISTS public.events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  description text,
  reward_points int NOT NULL DEFAULT 0 CHECK (reward_points >= 0),
  starts_at timestamptz,
  ends_at timestamptz,
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "events_public_read_active" ON public.events;
CREATE POLICY "events_public_read_active" ON public.events
  FOR SELECT USING (active = true AND (starts_at IS NULL OR starts_at <= now()) AND (ends_at IS NULL OR ends_at >= now()));

-- ---------------------------------------------------------------------------
-- 5) 민감 컬럼 직접 수정 방지 (일반 사용자가 role 등 변경 불가)
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.users_protect_sensitive_columns()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  is_admin boolean;
BEGIN
  IF TG_OP <> 'UPDATE' THEN
    RETURN NEW;
  END IF;
  IF NEW.role IS DISTINCT FROM OLD.role
     OR NEW.account_status IS DISTINCT FROM OLD.account_status
     OR NEW.mining_disabled IS DISTINCT FROM OLD.mining_disabled THEN
    -- SQL Editor 등: JWT 없음(auth.uid() NULL)이면 대시보드 직접 실행으로 간주해 허용(최초 관리자 지정)
    IF auth.uid() IS NULL THEN
      RETURN NEW;
    END IF;
    SELECT EXISTS (SELECT 1 FROM public.users u WHERE u.id = auth.uid() AND u.role = 'admin')
    INTO is_admin;
    IF NOT is_admin THEN
      RAISE EXCEPTION 'Forbidden: role/status/mining flags can only be changed by admins'
        USING ERRCODE = '42501';
    END IF;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tr_users_protect_sensitive ON public.users;
CREATE TRIGGER tr_users_protect_sensitive
  BEFORE UPDATE ON public.users
  FOR EACH ROW
  EXECUTE FUNCTION public.users_protect_sensitive_columns();

-- ---------------------------------------------------------------------------
-- 6) 내부: 관리자 여부 (클라이언트에 GRANT 하지 않음)
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public._admin_assert()
RETURNS void
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'Not authenticated' USING ERRCODE = '28000';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM public.users u WHERE u.id = auth.uid() AND u.role = 'admin') THEN
    RAISE EXCEPTION 'Admin only' USING ERRCODE = '42501';
  END IF;
END;
$$;

REVOKE ALL ON FUNCTION public._admin_assert() FROM PUBLIC;

-- ---------------------------------------------------------------------------
-- 7) 감사 기록 헬퍼
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public._admin_write_audit(
  p_action text,
  p_target uuid,
  p_payload jsonb
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.admin_audit_log (admin_id, action, target_user_id, payload)
  VALUES (auth.uid(), p_action, p_target, coalesce(p_payload, '{}'::jsonb));
END;
$$;

REVOKE ALL ON FUNCTION public._admin_write_audit(text, uuid, jsonb) FROM PUBLIC;

-- ---------------------------------------------------------------------------
-- 8) RPC: 사용자 목록 (검색/필터)
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.admin_list_users(
  p_search text DEFAULT NULL,
  p_role text DEFAULT NULL,
  p_status text DEFAULT NULL,
  p_limit int DEFAULT 50,
  p_offset int DEFAULT 0
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  lim int := least(greatest(coalesce(p_limit, 50), 1), 200);
  off int := greatest(coalesce(p_offset, 0), 0);
  total bigint;
  rows jsonb;
BEGIN
  PERFORM public._admin_assert();

  SELECT count(*) INTO total
  FROM public.users u
  WHERE (p_search IS NULL OR p_search = '' OR u.email ILIKE '%' || p_search || '%' OR u.nickname ILIKE '%' || p_search || '%' OR u.invite_code ILIKE '%' || p_search || '%')
    AND (p_role IS NULL OR p_role = '' OR u.role = p_role)
    AND (p_status IS NULL OR p_status = '' OR u.account_status = p_status);

  SELECT coalesce(jsonb_agg(to_jsonb(t) ORDER BY t.created_at DESC), '[]'::jsonb) INTO rows
  FROM (
    SELECT u.id, u.email, u.nickname, u.point, u.role, u.account_status, u.mining_disabled,
           u.invite_code, u.created_at, u.last_mined_at,
           (SELECT COALESCE(SUM(m.amount), 0)::bigint FROM public.mining_logs m
            WHERE m.user_id = u.id AND m.type = 'MINING' AND m.amount > 0) AS total_mined,
           (SELECT MAX(m.created_at) FROM public.mining_logs m WHERE m.user_id = u.id) AS last_log_at
    FROM public.users u
    WHERE (p_search IS NULL OR p_search = '' OR u.email ILIKE '%' || p_search || '%' OR u.nickname ILIKE '%' || p_search || '%' OR u.invite_code ILIKE '%' || p_search || '%')
      AND (p_role IS NULL OR p_role = '' OR u.role = p_role)
      AND (p_status IS NULL OR p_status = '' OR u.account_status = p_status)
    ORDER BY u.created_at DESC
    LIMIT lim OFFSET off
  ) t;

  RETURN jsonb_build_object('ok', true, 'total', total, 'rows', rows);
END;
$$;

GRANT EXECUTE ON FUNCTION public.admin_list_users(text, text, text, int, int) TO authenticated;

-- ---------------------------------------------------------------------------
-- 9) RPC: 권한 / 계정 상태 / 채굴 차단
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.admin_set_user_role(p_user_id uuid, p_role text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  PERFORM public._admin_assert();
  IF p_role NOT IN ('user', 'vip', 'admin') THEN
    RETURN jsonb_build_object('ok', false, 'message', 'Invalid role');
  END IF;
  IF p_user_id = auth.uid() AND p_role <> 'admin' THEN
    RETURN jsonb_build_object('ok', false, 'message', 'Cannot demote yourself');
  END IF;
  UPDATE public.users SET role = p_role WHERE id = p_user_id;
  IF NOT FOUND THEN
    RETURN jsonb_build_object('ok', false, 'message', 'User not found');
  END IF;
  PERFORM public._admin_write_audit('set_user_role', p_user_id, jsonb_build_object('role', p_role));
  RETURN jsonb_build_object('ok', true);
END;
$$;

GRANT EXECUTE ON FUNCTION public.admin_set_user_role(uuid, text) TO authenticated;

CREATE OR REPLACE FUNCTION public.admin_set_account_status(p_user_id uuid, p_status text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  PERFORM public._admin_assert();
  IF p_status NOT IN ('active', 'suspended', 'deleted') THEN
    RETURN jsonb_build_object('ok', false, 'message', 'Invalid status');
  END IF;
  UPDATE public.users SET account_status = p_status WHERE id = p_user_id;
  IF NOT FOUND THEN
    RETURN jsonb_build_object('ok', false, 'message', 'User not found');
  END IF;
  PERFORM public._admin_write_audit('set_account_status', p_user_id, jsonb_build_object('status', p_status));
  RETURN jsonb_build_object('ok', true);
END;
$$;

GRANT EXECUTE ON FUNCTION public.admin_set_account_status(uuid, text) TO authenticated;

CREATE OR REPLACE FUNCTION public.admin_set_mining_disabled(p_user_id uuid, p_disabled boolean)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  PERFORM public._admin_assert();
  UPDATE public.users SET mining_disabled = p_disabled WHERE id = p_user_id;
  IF NOT FOUND THEN
    RETURN jsonb_build_object('ok', false, 'message', 'User not found');
  END IF;
  PERFORM public._admin_write_audit('set_mining_disabled', p_user_id, jsonb_build_object('disabled', p_disabled));
  RETURN jsonb_build_object('ok', true);
END;
$$;

GRANT EXECUTE ON FUNCTION public.admin_set_mining_disabled(uuid, boolean) TO authenticated;

-- ---------------------------------------------------------------------------
-- 10) RPC: 포인트 수동 지급/차감 (단일 트랜잭션 + mining_logs + 감사)
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.admin_adjust_points(p_user_id uuid, p_delta bigint, p_reason text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  cur bigint;
  new_pt bigint;
  rsn text := left(coalesce(nullif(trim(p_reason), ''), 'admin_adjust'), 500);
BEGIN
  PERFORM public._admin_assert();
  IF p_user_id IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'message', 'Invalid user');
  END IF;
  IF p_delta = 0 THEN
    RETURN jsonb_build_object('ok', false, 'message', 'Delta cannot be zero');
  END IF;

  SELECT coalesce(point, 0) INTO cur FROM public.users WHERE id = p_user_id FOR UPDATE;
  IF NOT FOUND THEN
    RETURN jsonb_build_object('ok', false, 'message', 'User not found');
  END IF;

  new_pt := cur + p_delta;
  IF new_pt < 0 THEN
    RETURN jsonb_build_object('ok', false, 'message', 'Insufficient points', 'current', cur, 'delta', p_delta);
  END IF;

  UPDATE public.users SET point = new_pt WHERE id = p_user_id;
  INSERT INTO public.mining_logs (user_id, amount, type, slot_number)
  VALUES (p_user_id, p_delta::int, 'ADMIN_ADJUST', NULL);

  PERFORM public._admin_write_audit(
    'adjust_points',
    p_user_id,
    jsonb_build_object('delta', p_delta, 'reason', rsn, 'balance_after', new_pt)
  );

  RETURN jsonb_build_object('ok', true, 'balance', new_pt);
EXCEPTION
  WHEN OTHERS THEN
    RETURN jsonb_build_object('ok', false, 'message', SQLERRM);
END;
$$;

GRANT EXECUTE ON FUNCTION public.admin_adjust_points(uuid, bigint, text) TO authenticated;

-- ---------------------------------------------------------------------------
-- 11) RPC: 포인트(활동) 내역 — mining_logs
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.admin_list_mining_logs(
  p_user_id uuid DEFAULT NULL,
  p_type text DEFAULT NULL,
  p_limit int DEFAULT 100,
  p_offset int DEFAULT 0
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  lim int := least(greatest(coalesce(p_limit, 100), 1), 500);
  off int := greatest(coalesce(p_offset, 0), 0);
  total bigint;
  rows jsonb;
BEGIN
  PERFORM public._admin_assert();

  SELECT count(*) INTO total
  FROM public.mining_logs m
  WHERE (p_user_id IS NULL OR m.user_id = p_user_id)
    AND (p_type IS NULL OR p_type = '' OR m.type = p_type);

  SELECT coalesce(jsonb_agg(to_jsonb(x) ORDER BY x.created_at DESC), '[]'::jsonb) INTO rows
  FROM (
    SELECT m.id, m.user_id, m.amount, m.type, m.slot_number, m.created_at,
           u.email AS user_email, u.nickname AS user_nickname
    FROM public.mining_logs m
    LEFT JOIN public.users u ON u.id = m.user_id
    WHERE (p_user_id IS NULL OR m.user_id = p_user_id)
      AND (p_type IS NULL OR p_type = '' OR m.type = p_type)
    ORDER BY m.created_at DESC
    LIMIT lim OFFSET off
  ) x;

  RETURN jsonb_build_object('ok', true, 'total', total, 'rows', rows);
END;
$$;

GRANT EXECUTE ON FUNCTION public.admin_list_mining_logs(uuid, text, int, int) TO authenticated;

-- ---------------------------------------------------------------------------
-- 12) RPC: 환전 요청 목록 / 승인 / 거절
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.admin_list_withdrawals(
  p_status text DEFAULT 'pending',
  p_limit int DEFAULT 50,
  p_offset int DEFAULT 0
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  lim int := least(greatest(coalesce(p_limit, 50), 1), 200);
  off int := greatest(coalesce(p_offset, 0), 0);
  total bigint;
  rows jsonb;
BEGIN
  PERFORM public._admin_assert();

  SELECT count(*) INTO total
  FROM public.withdrawal_requests w
  WHERE p_status IS NULL OR p_status = '' OR w.status = p_status;

  SELECT coalesce(jsonb_agg(t.*), '[]'::jsonb) INTO rows
  FROM (
    SELECT w.*, u.email AS user_email, u.nickname
    FROM public.withdrawal_requests w
    LEFT JOIN public.users u ON u.id = w.user_id
    WHERE p_status IS NULL OR p_status = '' OR w.status = p_status
    ORDER BY w.created_at DESC
    LIMIT lim OFFSET off
  ) t;

  RETURN jsonb_build_object('ok', true, 'total', total, 'rows', rows);
END;
$$;

GRANT EXECUTE ON FUNCTION public.admin_list_withdrawals(text, int, int) TO authenticated;

CREATE OR REPLACE FUNCTION public.admin_decide_withdrawal(p_id bigint, p_approve boolean, p_note text DEFAULT NULL)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  w record;
  cur bigint;
  new_pt bigint;
BEGIN
  PERFORM public._admin_assert();

  SELECT * INTO w FROM public.withdrawal_requests WHERE id = p_id FOR UPDATE;
  IF NOT FOUND THEN
    RETURN jsonb_build_object('ok', false, 'message', 'Request not found');
  END IF;
  IF w.status <> 'pending' THEN
    RETURN jsonb_build_object('ok', false, 'message', 'Already decided');
  END IF;

  IF p_approve THEN
    SELECT coalesce(point, 0) INTO cur FROM public.users WHERE id = w.user_id FOR UPDATE;
    IF NOT FOUND THEN
      RETURN jsonb_build_object('ok', false, 'message', 'User missing');
    END IF;
    IF cur < w.amount THEN
      RETURN jsonb_build_object('ok', false, 'message', 'User has insufficient points');
    END IF;
    new_pt := cur - w.amount;
    UPDATE public.users SET point = new_pt WHERE id = w.user_id;
    INSERT INTO public.mining_logs (user_id, amount, type, slot_number)
    VALUES (w.user_id, (-w.amount)::int, 'WITHDRAW_APPROVED', NULL);
  END IF;

  UPDATE public.withdrawal_requests
  SET status = CASE WHEN p_approve THEN 'approved' ELSE 'rejected' END,
      decided_at = now(),
      decided_by = auth.uid(),
      note = coalesce(nullif(trim(p_note), ''), note)
  WHERE id = p_id;

  PERFORM public._admin_write_audit(
    'withdrawal_decision',
    w.user_id,
    jsonb_build_object('request_id', p_id, 'approved', p_approve, 'amount', w.amount)
  );

  RETURN jsonb_build_object('ok', true);
EXCEPTION
  WHEN OTHERS THEN
    RETURN jsonb_build_object('ok', false, 'message', SQLERRM);
END;
$$;

GRANT EXECUTE ON FUNCTION public.admin_decide_withdrawal(bigint, boolean, text) TO authenticated;

-- ---------------------------------------------------------------------------
-- 13) RPC: 통계 요약
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.admin_stats_summary()
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  issued bigint;
  spent bigint;
  user_count_active bigint;
  user_count_suspended bigint;
  total_mining bigint;
  today_mining bigint;
  abnormal_users bigint;
BEGIN
  PERFORM public._admin_assert();

  SELECT coalesce(sum(amount), 0) INTO issued FROM public.mining_logs WHERE amount > 0;
  SELECT coalesce(sum(-amount), 0) INTO spent FROM public.mining_logs WHERE amount < 0;
  SELECT count(*) INTO user_count_active FROM public.users WHERE account_status = 'active';
  SELECT count(*) INTO user_count_suspended FROM public.users WHERE account_status = 'suspended';
  SELECT coalesce(sum(amount), 0) INTO total_mining FROM public.mining_logs WHERE type = 'MINING' AND amount > 0;
  SELECT coalesce(sum(amount), 0) INTO today_mining
  FROM public.mining_logs
  WHERE type = 'MINING' AND amount > 0 AND created_at >= date_trunc('day', now());

  SELECT count(*)::bigint INTO abnormal_users
  FROM (
    SELECT 1
    FROM public.mining_logs m
    WHERE m.type = 'MINING' AND m.created_at > now() - interval '24 hours'
    GROUP BY m.user_id
    HAVING count(*) > 12
  ) s;

  RETURN jsonb_build_object(
    'ok', true,
    'points_positive_sum', issued,
    'points_negative_abs_sum', spent,
    'active_users', user_count_active,
    'suspended_users', user_count_suspended,
    'total_mining_sum', total_mining,
    'today_mining_sum', today_mining,
    'abnormal_mining_users_24h', abnormal_users
  );
END;
$$;

GRANT EXECUTE ON FUNCTION public.admin_stats_summary() TO authenticated;

-- ---------------------------------------------------------------------------
-- 14) RPC: 감사 로그 조회 (관리자)
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.admin_list_audit_log(p_limit int DEFAULT 100, p_offset int DEFAULT 0)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  lim int := least(greatest(coalesce(p_limit, 100), 1), 500);
  off int := greatest(coalesce(p_offset, 0), 0);
  rows jsonb;
BEGIN
  PERFORM public._admin_assert();

  SELECT coalesce(jsonb_agg(to_jsonb(t) ORDER BY t.created_at DESC), '[]'::jsonb) INTO rows
  FROM (
    SELECT
      a.id,
      a.admin_id,
      a.action,
      a.target_user_id,
      a.payload,
      a.created_at,
      adm.email AS admin_email,
      adm.nickname AS admin_nickname,
      tgt.email AS target_email,
      tgt.nickname AS target_nickname
    FROM public.admin_audit_log a
    LEFT JOIN public.users adm ON adm.id = a.admin_id
    LEFT JOIN public.users tgt ON tgt.id = a.target_user_id
    ORDER BY a.created_at DESC
    LIMIT lim OFFSET off
  ) t;

  RETURN jsonb_build_object('ok', true, 'rows', rows);
END;
$$;

GRANT EXECUTE ON FUNCTION public.admin_list_audit_log(int, int) TO authenticated;

-- ---------------------------------------------------------------------------
-- 15) RPC: 미션 / 이벤트 CRUD (관리자)
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.admin_list_missions(p_include_inactive boolean DEFAULT true)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  rows jsonb;
BEGIN
  PERFORM public._admin_assert();

  SELECT coalesce(jsonb_agg(to_jsonb(t)), '[]'::jsonb) INTO rows
  FROM (
    SELECT * FROM public.missions m
    WHERE p_include_inactive OR m.active = true
    ORDER BY m.id DESC
  ) t;

  RETURN jsonb_build_object('ok', true, 'rows', rows);
END;
$$;

GRANT EXECUTE ON FUNCTION public.admin_list_missions(boolean) TO authenticated;

CREATE OR REPLACE FUNCTION public.admin_upsert_mission(
  p_id bigint,
  p_title text,
  p_description text,
  p_reward_points int,
  p_active boolean
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  PERFORM public._admin_assert();
  IF p_id IS NULL THEN
    INSERT INTO public.missions (title, description, reward_points, active)
    VALUES (p_title, p_description, p_reward_points, p_active);
  ELSE
    UPDATE public.missions
    SET title = p_title, description = p_description, reward_points = p_reward_points,
        active = p_active, updated_at = now()
    WHERE id = p_id;
    IF NOT FOUND THEN
      RETURN jsonb_build_object('ok', false, 'message', 'Mission not found');
    END IF;
  END IF;
  PERFORM public._admin_write_audit('mission_upsert', NULL, jsonb_build_object('id', p_id, 'title', p_title));
  RETURN jsonb_build_object('ok', true);
END;
$$;

GRANT EXECUTE ON FUNCTION public.admin_upsert_mission(bigint, text, text, int, boolean) TO authenticated;

CREATE OR REPLACE FUNCTION public.admin_list_events(p_include_inactive boolean DEFAULT true)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  rows jsonb;
BEGIN
  PERFORM public._admin_assert();

  SELECT coalesce(jsonb_agg(to_jsonb(t)), '[]'::jsonb) INTO rows
  FROM (
    SELECT * FROM public.events e
    WHERE p_include_inactive OR e.active = true
    ORDER BY e.id DESC
  ) t;

  RETURN jsonb_build_object('ok', true, 'rows', rows);
END;
$$;

GRANT EXECUTE ON FUNCTION public.admin_list_events(boolean) TO authenticated;

CREATE OR REPLACE FUNCTION public.admin_upsert_event(
  p_id bigint,
  p_title text,
  p_description text,
  p_reward_points int,
  p_starts_at timestamptz,
  p_ends_at timestamptz,
  p_active boolean
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  PERFORM public._admin_assert();
  IF p_id IS NULL THEN
    INSERT INTO public.events (title, description, reward_points, starts_at, ends_at, active)
    VALUES (p_title, p_description, p_reward_points, p_starts_at, p_ends_at, p_active);
  ELSE
    UPDATE public.events
    SET title = p_title, description = p_description, reward_points = p_reward_points,
        starts_at = p_starts_at, ends_at = p_ends_at, active = p_active, updated_at = now()
    WHERE id = p_id;
    IF NOT FOUND THEN
      RETURN jsonb_build_object('ok', false, 'message', 'Event not found');
    END IF;
  END IF;
  PERFORM public._admin_write_audit('event_upsert', NULL, jsonb_build_object('id', p_id, 'title', p_title));
  RETURN jsonb_build_object('ok', true);
END;
$$;

GRANT EXECUTE ON FUNCTION public.admin_upsert_event(bigint, text, text, int, timestamptz, timestamptz, boolean) TO authenticated;

-- ---------------------------------------------------------------------------
-- 16) RPC: 일별 채굴(MINING) 추이 · 상위 채굴자 (v2)
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.admin_mining_daily_stats(p_days int DEFAULT 14)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  d int := least(greatest(coalesce(p_days, 14), 1), 90);
  rows jsonb;
BEGIN
  PERFORM public._admin_assert();

  SELECT coalesce(jsonb_agg(to_jsonb(t) ORDER BY t.day ASC), '[]'::jsonb) INTO rows
  FROM (
    SELECT (date_trunc('day', m.created_at))::date AS day,
           coalesce(sum(m.amount), 0)::bigint AS total_mined
    FROM public.mining_logs m
    WHERE m.type = 'MINING' AND m.amount > 0
      AND m.created_at >= date_trunc('day', now()) - make_interval(days => (d - 1))
    GROUP BY 1
    ORDER BY 1
  ) t;

  RETURN jsonb_build_object('ok', true, 'rows', rows);
END;
$$;

GRANT EXECUTE ON FUNCTION public.admin_mining_daily_stats(int) TO authenticated;

CREATE OR REPLACE FUNCTION public.admin_mining_top_miners(p_limit int DEFAULT 10)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  lim int := least(greatest(coalesce(p_limit, 10), 1), 50);
  rows jsonb;
BEGIN
  PERFORM public._admin_assert();

  SELECT coalesce(jsonb_agg(to_jsonb(t) ORDER BY t.total_mined DESC), '[]'::jsonb) INTO rows
  FROM (
    SELECT u.id, u.email, u.nickname,
           coalesce(sum(m.amount), 0)::bigint AS total_mined
    FROM public.users u
    INNER JOIN public.mining_logs m ON m.user_id = u.id AND m.type = 'MINING' AND m.amount > 0
    GROUP BY u.id, u.email, u.nickname
    ORDER BY total_mined DESC
    LIMIT lim
  ) t;

  RETURN jsonb_build_object('ok', true, 'rows', rows);
END;
$$;

GRANT EXECUTE ON FUNCTION public.admin_mining_top_miners(int) TO authenticated;
